### ISSUE TITLE
ng serve cannot Initialize

### ISSUE THREAD

**Issue by brilliantwf** [aws-samples/aws-rekognition-liveness-detection#1]
ng serve
⠼ Generating browser application bundles (phase: sealing)...
<--- Last few GCs --->

[50081:0x7fd847200000]   111883 ms: Scavenge (reduce) 2040.4 (2081.9) -> 2040.1 (2082.1) MB, 4.2 / 0.0 ms  (average mu = 0.134, current mu = 0.198) allocation failure
[50081:0x7fd847200000]   111892 ms: Scavenge (reduce) 2040.7 (2082.1) -> 2040.4 (2082.4) MB, 5.5 / 0.0 ms  (average mu = 0.134, current mu = 0.198) allocation failure

<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x101964025 node::Abort() [/usr/local/bin/node]
 2: 0x1019641a8 node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
 3: 0x101ace127 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 4: 0x101ace0c3 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 5: 0x101c6f375 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/usr/local/bin/node]
 6: 0x101c733ab v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/usr/local/bin/node]
 7: 0x101c6fc7c v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/local/bin/node]
 8: 0x101c6d12a v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
 9: 0x101c7a550 v8::internal::Heap::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
10: 0x101c7a5d1 v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
11: 0x101c4176d v8::internal::FactoryBase<v8::internal::Factory>::NewRawOneByteString(int, v8::internal::AllocationType) [/usr/local/bin/node]
12: 0x101f15a18 v8::internal::String::SlowFlatten(v8::internal::Isolate*, v8::internal::Handle<v8::internal::ConsString>, v8::internal::AllocationType) [/usr/local/bin/node]
13: 0x102004bc1 v8::internal::Runtime_StringSplit(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
14: 0x1023969b9 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/usr/local/bin/node]
15: 0x10238abb7 Builtins_StringPrototypeSplit [/usr/local/bin/node]
16: 0x10724fe74
[1]    50081 abort      ng serve

**Comment by brilliantwf** [comment]
issue solved ,export NODE_OPTIONS=--max_old_space_size=8096

**Comment by Maestroharyor** [comment]
@brilliantwf 
Where should this be added?
