### ISSUE TITLE
Rekognitniton bad request 400

### ISSUE THREAD

**Issue by TvojTatk0** [aws-samples/aws-rekognition-liveness-detection#2]
Hi. I was following this tutorial but got stuck on point 12. 
After successful user creation I got HTTP 400 bad request on call:
`https://rekognition.eu-central-1.amazonaws.com/`

With response:
```
{"__type":"AccessDeniedException"}
```

What I notice is that payload is empty.:
![image](https://github.com/aws-samples/aws-rekognition-liveness-detection/assets/28844291/dbe3b97b-1a4e-4161-b3c6-918154c1ad01)

Can somebody help to figure out what is wrong? Thanks

**Comment by Fraser27** [comment]
@StigoSvK Amazon Rekognition Face liveness feature is currently supported for the below regions AWS regions
US East (N. Virginia), US West (Oregon), Europe (Ireland), and Asia Pacific (Tokyo, Mumbai).
I think you're trying it out in Frankfurt region which could be causing the issue. 
You could try it out in eu-west-1 (Ireland).
Link
https://aws.amazon.com/about-aws/whats-new/2023/04/amazon-rekognition-face-liveness-deter-fraud-facial-verification/

**Comment by TvojTatk0** [comment]
@Fraser27 I switched to `eu-west-1` and it's working now.
I cannot thank you enough.

**Comment by Fraser27** [comment]
Fixed. Amazon Rekognition Face liveness feature is currently supported for the below regions AWS regions
US East (N. Virginia), US West (Oregon), Europe (Ireland), and Asia Pacific (Tokyo, Mumbai).
