### ISSUE TITLE
Access to fetch at 'https://www.kaggle.com' blocked by CORS policy: No 'Access-Control-Allow-Origin'

### ISSUE THREAD

**Issue by heccer** [aws-samples/aws-rekognition-liveness-detection#5]
Hi!

I've been using this proyect for a month already.
It has been working fine until yesterday! :(

Yesterday I received this error message (CORS Policy) which I didn't receive before.

Access to fetch at 'https://www.kaggle.com/models/tensorflow/blazeface/frameworks/tfJs/variations/default/versions/1/model.json?tfjs-format=file&tfhub-redirect=true' (redirected from '[https://tfhub.dev/tensorflow/tfjs-model/blazeface/1/default/1/model.json?tfjs-format=file'](https://tfhub.dev/tensorflow/tfjs-model/blazeface/1/default/1/model.json?tfjs-format=file%27)) from origin 'https://cert-austrobank-homebanking.fit-bank.com/' **has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource**. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

I suspect that "kaggle.com" started to block my requests, but I don't know where to add the "no-cors" mode in the proyect :(
Can you explain where can I add that parameters in order to skip CORS Validation ?

Thanks in advice!

**Comment by Fraser27** [comment]
You could try adding custom headers for http responses and add in your CORS headers in there.
https://docs.aws.amazon.com/amplify/latest/userguide/custom-headers.html#setting-custom-headers

**Comment by BryGuz** [comment]
Try updating component's version
